### PR TITLE
adding react-native-code-push feature

### PR DESCRIPTION
**Pull request by dan-nyanko**
Implements [react-native-code-push](https://microsoft.github.io/code-push/docs/react-native.html)
# Installation

```
npm install -g code-push-cli
code-push register
```

You'll need to be added as a collaborator to the Code Push app, PM me for the details (you must register with code push above to be added as collaborator).  See [here](https://github.com/Microsoft/code-push/tree/master/cli#app-collaboration)
# Settings

Once you've registered and been added as collaborator, you may obtain your keys by `code-push deployment ls <appName> [--displayKeys|-k]`
## iOS - Settings.xcconfig

On iOS, the file `Settings.xcconfig` (its a text file that has the following format) needs added to `ios/` directory.

```
//
//  Settings.xcconfig
CODE_PUSH_KEY[config=Staging]=<your_collaboration_key>
CODE_PUSH_KEY[config=Release]=<your_collaboration_key>
```
## Android - gradle.properties

On Android, the file `gradle.properties` (its a text file that has the following format) needs added to a hidden folder on your home directory `~/.gradle/gradle.properties`.

```
#
# gradle.properties
CODE_PUSH_STAGING_KEY=<your_collaboration_key>
CODE_PUSH_PRODUCTION_KEY=<your_collaboration_key>
```
# Testing
## iOS

To test on iOS, you'll need to change the scheme to `staging` and build to a real device.  Once the branch as been built, launch the app.  The branch `code-push-test` was already uploaded to `Staging` so it will relaunch once the update has been downloaded.  It may require restarting the application. If successful, you'll notice the styling has changed.
## Android

To test on Android, you'll just need to run `cd android/` then `./gradlew installStaging` to either an emulator or device connected via USB.  It will download from `Staging` and if successful, you'll notice the styling has changed.

### CODE REVIEW

**Comment by sophiabersani** [comment]
Unable to build this PR so far.

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/bersani/dev/GoodQuestion/android/app/build.gradle' line: 105

* What went wrong:
A problem occurred evaluating project ':app'.
> Neither path nor baseDir may be null or empty string. path='' basedir='/Users/bersani/dev/GoodQuestion/android/app'
```

Seems to be due to a misconfiguration on `gradle.properties`.
Am I missing any settings file?

**Comment by dan-nyanko** [comment]
@gbersani Please see the instructions above on setting `~/.gradle/gradle.properties`

**Comment by sophiabersani** [comment]
I have followed the instructions, and attempted again on other devices.

The error seems to be related to `GOODQUESTION_RELEASE_STORE_FILE` value missing from my `gradle.properties`.
This was not a value which we needed for dev builds before this branch.

Would it be possible to get the most recent versions of this file pinned in our Slack?

**Comment by dan-nyanko** [comment]
@gbersani You won't need to build a signed .apk to test this feature.  It is sufficient to perform `cd android/ && ./gradlew installDebug`.  Please post stacktrace of the error.  

These values were previously assigned to empty strings, but null values compile just fine.  Please see the default [gradle.properties](https://github.com/ecohealthalliance/GoodQuestion/blob/9ba273478879329bf12a40038be475af2716803d/android/gradle.properties#L21-L24)

**Comment by dan-nyanko** [comment]
updated for RN >= .29 and GQ v2

**Pull request merged**
