### PR TITLE
Boilerplating

### PR DESCRIPTION
**Pull request by sophiabersani**
Boilerplates architecture for the React native app
- Implements navigation components for iOS and Android.
- Creates a store object for syncing data.
- Adds a wrapper component for bridging component props
- Adds reusable style objects for holding css variables
- Includes a short learning module to get the team used to the React life cycle

### CODE REVIEW

**Comment by dan-nyanko** [comment]
@gbersani 
This is a great start.  Let's get the flow to match our wireframes:
1. We don't need the WelcomePage.js view and should go straight to the SurveyListPage.js view.
2. We should remove the [next] action from NavigationBarConfig.  Navigation will occur from clicking on a survey item in the list (SurveyFormPage.js) or the hamburger menu that will be done in the near future.
3. We should place the duplicate code in RouteMapper, NavigationBarConfig within `index.android.js` and  `index.ios.js` into their own modules.  Ex: `js/router/RouteMapper.js`, `js/router/NavigationBarConfig.js`.

**Comment by sophiabersani** [comment]
Hi Dan,
1. The Welcome screen should be there as part of the loading, navigation is not ready yet, so for now the only way to move along views is by that "Next" button in the navbar.
2. See 1. The routing and navigation will be the most complex part of this phase for the UI portion. The proper workflow should be implemented next, but I will need to create a custom component for that.
3. I shall do that, a lot of the code for the router is redundant at the moment. iOS and Android routing is currently set individually, part of my router-building goal is to unify them into a single file once I research exactly how we want to approach this.

Thanks.

**Comment by dan-nyanko** [comment]
@gbersani - Please open a separate branch for each story

**Comment by dan-nyanko** [comment]
@gbersani 

1.
We do not need a Welcome screens as part of loading.  If you are thinking of a splash screen, well that is a requirement on iOS called the `LaunchScreen` but not on Android.  The iOS splash screen is defined within xcode as the [LaunchScreen](https://github.com/ecohealthalliance/GoodQuestion/blob/master/ios/GoodQuestion/Base.lproj/LaunchScreen.xib)

We can fake a splash screen on Android, but its not a standard UI pattern on that platform.
The first view should be the SurveyListPage.

2.
Pressing 'Next' on a navigation bar is not a UI pattern on either device.  It was great for demonstration purposes but we are moving past the demo stage.

Please contact me on Slack if you have any additional questions.

**Pull request merged**
