### PR TITLE
Adds support for push notifications received on the foreground

### PR DESCRIPTION
**Pull request by sophiabersani**
Stories:
https://www.pivotaltracker.com/story/show/126404897
https://www.pivotaltracker.com/story/show/121941821
https://www.pivotaltracker.com/story/show/127087783

Changes:
- Moves most of the notification logic to `api/Notifications.js` to avoid bloating the `SharedNavigator` component.
- Adds discrete UI notices for when notifications are received on the foreground.
- Adds a menu counter for new notifications.
- Adds option to quickly clear in-app notifications.
- Properly delete notifications when selected in `NotificationsPage`.
- Changes unique ids on Notification objects to match the ones received by Push. (Local notifications still keep their formIDs as their primary key)

Bug fixes:
- Updates realm.io and limits some of the usage in the background to avoid a crash caused when new push notifications were received. (Android)

### CODE REVIEW

**Comment by dan-nyanko** [comment]
The remote notification doesn't include its uniqueId (which is combination of user.id and form.id).  The data only includes the [formId](https://github.com/ecohealthalliance/mobile-survey/blob/master/app/packages/_notifications/index.coffee#L95-L112).
- How are notifications ensured to be unique for each user locally if just using form.id?
- How are Realm cached remote notifications getting their primary key `id`?  (This is in reference to your last bullet `Changes unique ids on Notification objects to match the ones received by Push`)

**Comment by sophiabersani** [comment]
Updated the PR to handle user-specific notifications on both receiving and viewing cases.

Once V2 is merged I'd like to further improve on this to only turn on these services when the use is logged in.

**Comment by dan-nyanko** [comment]
@gbersani bump.  Please take a look at my previous comment.

**Comment by sophiabersani** [comment]
Sorry, I should have been a bit more clear on my previous comment.

I have fixed the PR to take into consideration the users targeted by the Push Notifications, it was not doing that before you mentioned it.
- In-App Notifications are assigned to the user currently logged in, this way anything received via the active Installation object will be viewable only by the user in which it was assigned to.
- PushNotifications come with a `push_id` variable from Parse. I'm using that value as the primary key for in-app notifications stored in Realm so they are in sync.

I'd like to add that this PR targets `master` and doesn't have in-app notifications for geofence crossings, the ids for those will have to be generated on the spot.

**Comment by dan-nyanko** [comment]
@gbersani the `push_id` != `notification.id`.  The server has a collection which is called `Notification` that is used to determine if a push notification was sent for the user. `push_id` is from an internal private collection `_PushStatus`.  

The logic in this PR does not synchronize the local cache with the remote collection, which is PT #121941821

The server Notification schema:

```
    _id:
    userId:
    triggerId:
    sent:
    message:
    created_at:
    updated_at:
```

The cache schema:

```
    formId:
    surveyId:
    title:
    description:
    datetime:
    complete:
```

IMO we should match the schema on the server and the cache as much as possible

**Comment by sophiabersani** [comment]
You're correct, it should. I've synced the Notifications to the PushNotification objects I was receiving from Parse, not the ones on the Meteor server.

The story's description on PT was a bit ambiguous on meaning, given our two server layers.

It's not a hard fix, I will resubmit this PR in a post-v2 version.

**Pull request closed without merging**
