### PR TITLE
Polish form page & questions

### PR DESCRIPTION
**Pull request by sophiabersani**
- Adds logout confirmation
- Styles questions with custom overflow.

Note: Some of these question style updates won’t come into effect with the current swiper.
There is a minor `overflow:’hidden’` change that needs to be done in Dan’s fork for it to behave like we want it to.

### CODE REVIEW

**Comment by sophiabersani** [comment]
Story:
https://www.pivotaltracker.com/story/show/120607619

**Comment by dan-nyanko** [comment]
@gbersani please clone the swiper fork and send me the PR for the update

**Comment by sophiabersani** [comment]
I'm unable to send you a PR, do you have your fork set to 'collaborators only' ?

**Comment by dan-nyanko** [comment]
@gbersani I don't see anything that would prevent this in the repo's options. What is the error?

**Comment by dan-nyanko** [comment]
@gbersani I just added you as collaborator

**Comment by sophiabersani** [comment]
`Please make sure you have the correct access rights and the repository exists.` When trying with command line, similar error message using the github desktop client.

I am pretty sure I am not targeting the original repo either.

**Comment by dan-nyanko** [comment]
I added you as a collaborator.  Did you accept the invite?

**Pull request merged**
