### PR TITLE
Adds support for active/expired/deleted surveys

### PR DESCRIPTION
**Pull request by sophiabersani**
Resubmission of PR#149, updated with compatibility with v2 features.

Story:
https://www.pivotaltracker.com/story/show/126138113

Changes:
- Adds a tab for expired surveys
- Adds a method for refreshing only the expired survey list
- Refactors pruning of deleted surveys.
- Refactors Survey fetching to prevent data from going missing as the number of Surveys increases in the backend.
  - Our current Parse fetching could not distinguish between active/inactive/deleted surveys.

Updates:
- Disables current triggers when surveys are deactivated or deleted.
- Disables current geofences when surveys are deactivated or deleted.
- Fixes some crashes caused by marking surveys as 'deleted' in Parse.
- Optimizes list filtering to reduce delay when filtering surveys.

### CODE REVIEW

**Comment by dan-nyanko** [comment]
@gbersani 
I went to create a demo survey that I could delete and/or expire and came across this bug:

```
GoodQuestion/tool-populate/api/Forms.js:93
<<<<<<< HEAD
^^
```

Would you mind updating this branch to fix so that I may test?

**Comment by sophiabersani** [comment]
Looks like a merger error.
Odd that it let me commit with that in there.

**Comment by dan-nyanko** [comment]
@gbersani 

I'm getting the following red screen upon authentication on this branch.

image

**Comment by dan-nyanko** [comment]
Steps:
1. Create demo geofence form using `node ./tool-populate/index.js -g`.
2. Launch the app with iPhone simulator
3. Click on the survey created in step 1.

image

**Comment by sophiabersani** [comment]
Updated a preventive fix to avoid that red screen when the Parse server dies.
Please test on a localserver until the SSL for our dev. server is working again.

**Comment by dan-nyanko** [comment]
@gbersani :+1: This PR looks great - it's ready to merge! :shipit:

**Pull request merged**
