### PR TITLE
User registration

### PR DESCRIPTION
**Pull request by dan-nyanko**
Note: you'll need an updated js/settings.js file from slack
- performs user registration and validation
- implements custom swipe interface with beforeChangePage handler
- implements logout in slideout menu
- improves use of setState efficiency in mixins
- new mixin `event-mixin` for form change handlers

### CODE REVIEW

**Comment by dan-nyanko** [comment]
https://www.pivotaltracker.com/story/show/119818265

**Comment by dan-nyanko** [comment]
https://www.pivotaltracker.com/story/show/119815089

**Comment by dan-nyanko** [comment]
https://www.pivotaltracker.com/story/show/119007651

**Comment by sophiabersani** [comment]
Some feedback:
- The error message for an invalid password is currently a RegEx, it should be readable to non-technical people.
  - In the first page of registration, the "Next" Button for iOS is being half-covered/hidden by the swiper page circles.
  - I'm getting a warning if the first thing I do after launching the app is attempt to login. It's a standard faulty `setState` call.

```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Navigator component.
```

No specific lines or files reported in the error, I'm afraid.
- The changes to the backgroundColor affected a few other unintended views as well. Questions now are being displayed in a pure blue BG.

**Comment by sophiabersani** [comment]
I was able to successfully register and login with my own credentials though. No issues there!

**Pull request merged**
