### PR TITLE
Adds Form List to access pending, complete and incomplete forms.

### PR DESCRIPTION
**Pull request by sophiabersani**
This is a resubmission of PR#153, updated with the merger of v1/v2.

Adds two related features aimed at giving the user better access to form editing.

Stories:
https://www.pivotaltracker.com/story/show/127007233
https://www.pivotaltracker.com/story/show/127007067
https://www.pivotaltracker.com/story/show/127939489

Changes:
- Saves form progress on the background, after each question.
- Adjusts form cache to allow querying for completed forms.
- Provides the user object as a prop to be used by view components.
- Adds a Form List page, with forms sorted in the following order:
  1) Forms left incomplete
  2) Geofence Forms in-range
  3) TimeTrigger Forms, ordered by trigger datetime values.
  4) Geofence Forms out-of-range
  5) Completed Forms

### CODE REVIEW

**Comment by dan-nyanko** [comment]
@gbersani The form view is interesting. Can you explain how this will effect FIFO concept of forms to be completed in a specific order? For example, I could select Form 3 prior to completing Form 1, which breaks this pattern.

**Comment by dan-nyanko** [comment]
@gbersani Also, I'm getting prompted to complete forms that were never started as I believe I stared answering Form 3 prior to Form 0, 1, 2.

**Comment by sophiabersani** [comment]
You are correct Dan, the form list was allowing datetime order to be skipped.
I've submitted a fix that should take care of that.

Thank you!

**Comment by dan-nyanko** [comment]
@gbersani 

I'm getting the same red screen here.  This may have been introduced in the last merge to master.

image

**Comment by dan-nyanko** [comment]
@gbersani Please update the iOS permissions on this branch

**Comment by sophiabersani** [comment]
@dan-nyanko updated with the fix from PR #161

**Comment by dan-nyanko** [comment]
@gbersani 

It seems the count is off by +1 within the sub headings.  `Form #2` is then `Available after form: Form #2` ... ?

image

**Comment by dan-nyanko** [comment]
@gbersani :+1: This PR looks great - it's ready to merge! :shipit:

**Pull request merged**
