### PR TITLE
Android local notifications

### PR DESCRIPTION
**Pull request by dan-nyanko**
https://www.pivotaltracker.com/story/show/120594229
https://www.pivotaltracker.com/story/show/120123167
- Refactors the java project
- Removes dependency on native Parse SDKs by creating `installation` objects via REST API.
- Uses private `react-native-android` in package.json for background geolocation on android

_Note: settings.js has been updated in slack channel_

Most likely need to do `rm -fr node_modules && npm install`

### CODE REVIEW

**Comment by sophiabersani** [comment]
I'm being unable to launch the iOS version on this branch.

```
In file included from /Users/bersani/dev/GoodQuestion/ios/GoodQuestion/main.m:12:
/Users/bersani/dev/GoodQuestion/ios/GoodQuestion/AppDelegate.h:11:9: fatal error: 
      'Parse/Parse.h' file not found
#import <Parse/Parse.h>
        ^
1 error generated.

** BUILD FAILED **
```

**Comment by dan-nyanko** [comment]
@gbersani let me know if [ee01fe6](https://github.com/ecohealthalliance/GoodQuestion/pull/100/commits/ee01fe68f9ec344d7e8a166fa32fa952780c723d) fixes the issue

**Comment by sophiabersani** [comment]
@dan-nyanko I can launch the app again, but am unable to login.
It's getting stuck at "Verifying..."

**Comment by sophiabersani** [comment]
Edit: The updated settings.js in Slack has the real servers commented out, which is why I couldn't login.

**Pull request merged**
